### ISSUE TITLE
Not working anymore...

### ISSUE THREAD

**Issue by Yomark1** [scheelings/GlashartEPGgrabber#3]
Was working great for some time, but I think they changed something. The main problem resulting in the Channels.xml file not generated correctly anymore when using /all. 
When I use an old Channels.xml file and then option /all-xmltv the EPG is downloaded correctly again.

Windows log:

```
d:\GlashartEPGgrabber>GlashartEPGgrabber.exe /all
Downloading TV menu to d:\GlashartEPGgrabber\Data\TvMenu\index.xhtml.gz
TV menu file downloaded
Uncompressing TV menu to d:\GlashartEPGgrabber\Data\TvMenu\index.html
Failed to extract d:\GlashartEPGgrabber\Data\TvMenu\index.xhtml.gz
ICSharpCode.SharpZipLib.GZip.GZipException: Error GZIP header, first magic byte
doesn't match
   at ICSharpCode.SharpZipLib.GZip.GZipInputStream.ReadHeader() in c:\projects\s
harpziplib-portable\src\GZip\GzipInputStream.cs:line 197
   at ICSharpCode.SharpZipLib.GZip.GZipInputStream.Read(Byte[] buffer, Int32 off
set, Int32 count) in c:\projects\sharpziplib-portable\src\GZip\GzipInputStream.c
s:line 148
   at ICSharpCode.SharpZipLib.Core.StreamUtils.Copy(Stream source, Stream destin
ation, Byte[] buffer) in c:\projects\sharpziplib-portable\src\Core\StreamUtils.c
s:line 124
   at GlashartLibrary.IO.CompressionHelper.Decompress(String gzipFileName, Strin
g filename) in c:\GlashartEPGgrabber\GlashartLibrary\IO\CompressionHelper.cs:lin
e 38
TV menu file uncompressed
Downloading TV menu script to d:\GlashartEPGgrabber\Data\TvMenu\code.js.gz
TV menu script file downloaded
Uncompressing TV menu script file to d:\GlashartEPGgrabber\Data\TvMenu\code.js
TV menu script file uncompressed
Parsing channels from the TV menu script file
Failed to read the channel number for h264
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffe
r& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo in
fo)
   at System.Int32.Parse(String s)
   at GlashartLibrary.Helpers.JavascriptHelper.ParseChannnels(String scriptFile)
 in c:\GlashartEPGgrabber\GlashartLibrary\Helpers\JavascriptHelper.cs:line 88
3 channels found in TV menu script file
Logging channel list to file d:\GlashartEPGgrabber\Data\TvMenu\Channels.xml
Channel XML file generated
Generating M3U file d:\GlashartEPGgrabber\Data\TvMenu\glashart.m3u based on chan
nels
M3U file generated
Downloading EPG files to folder d:\GlashartEPGgrabber\Data\EPG
EPG files downloaded
Decompressing EPG files in folder d:\GlashartEPGgrabber\Data\EPG
EPG files decompressed
Reading EPG files from folder d:\GlashartEPGgrabber\Data\EPG
EPG files read
Succesfully loaded details for 0 programs
Failed to load details for 0 programs
Generating XMLTV file d:\GlashartEPGgrabber\Data\guide.xml
XMLTV file generated
Read TvHeadend configuration from d:\GlashartEPGgrabber\Data\TvMenu
Directory D:\GlashartEPGgrabber\Data\TVheadend\input\iptv\networks doesn't exist

Directory D:\GlashartEPGgrabber\Data\TVheadend\channel\config doesn't exist
Directory D:\GlashartEPGgrabber\Data\TVheadend\channel\tag doesn't exist
Update TVheadend configuration based on channels
Create new TVH mux with service for NPO 1
Create new TVH tag for Radio
Create new TVH channel for NPO 1
Save updated TvHeadend configuration to d:\GlashartEPGgrabber\Data\TvMenu
Saved 1 networks to disk (1 Created; 0 Updated)
Saved 1 muxes to disk (1 Created; 0 Updated)
Saved 1 services to disk (1 Created; 0 Updated)
Saved 1 channels to disk (1 Created; 0 Updated)
Saved 1 tags to disk (1 Created; 0 Updated)
Glashart EPG Grabber ended

d:\GlashartEPGgrabber>
```

Beginning of incorrect XML file:

```
<?xml version="1.0" encoding="utf-8"?>
<ArrayOfChannel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Channel>
    <Key>hd</Key>
    <Locations />
    <Icons />
    <Radio>false</Radio>
    <Number>-1</Number>
  </Channel>
  <Channel>
    <Key>pvr</Key>
    <Locations />
    <Icons />
    <Radio>false</Radio>
    <Number>-1</Number>
  </Channel>
  <Channel>
    <Key>h264</Key>
    <Name>NPO 1</Name>
    <Locations>
      <ChannelLocation>
        <Name>HD+</Name>
        <Url>igmp://224.0.251.124:8248</Url>
      </ChannelLocation>
      <ChannelLocation>"
...
```

Correct XML file beginning:

```
<?xml version="1.0" encoding="utf-8"?>
<ArrayOfChannel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Channel>
    <Key>ned1</Key>
    <Name>NPO 1</Name>
    <Locations>
      <ChannelLocation>
        <Name>HD+</Name>
        <Url>igmp://224.0.251.124:8248</Url>
      </ChannelLocation>
      <ChannelLocation>
        <Name>ztv-sd</Name>
        <Url>igmp://239.192.4.101:6202</Url>
      </ChannelLocation>
      <ChannelLocation>
        <Name>HD</Name>
        <Url>igmp://224.0.252.126:7252</Url>
      </ChannelLocation>
      <ChannelLocation>
        <Name>SD</Name>
        <Url>igmp://224.0.251.1:8002</Url>
      </ChannelLocation>
      <ChannelLocation>
        <Name>ztv-hd</Name>
        <Url>igmp://239.193.252.126:7252</Url>
      </ChannelLocation>
    </Locations>
    <Icons>
      <string>npotv1.png</string>
    </Icons>
    <Radio>false</Radio>
    <Number>1</Number>
  </Channel>
  <Channel>
    <Key>ned2</Key>
    <Name>NPO 2</Name>
    <Locations>
      <ChannelLocation>
        <Name>HD+</Name>

```

Thank you very much for this. Using if under Linux/MOMO and also works fine there(although some paths are hardcoded and needed changing).

**Comment by scheelings** [comment]
HI Yomark1,

English?

OK, I will have a look soon. One tip though: use the “/ini-settings” argument and start using a .ini file in stead of the .config file on Linux. That works better!

Regards,
Danny

**Comment by Yomark1** [comment]
Hoi Danny, 
Nederlands :)

/ini-settings parameter was mij niet bekend. Staat ook niet in de help, of ik kijk er echt gigantisch overheen(wel het bestaan van de .ini file, maar deze leek niet gebruikt te worden....hierom dus :) ) 
Voor de tvheadend output(TvheadendNetworkInterface ) generatie heb ik daardoor de source aangepast in Visual Studio. Maar dit lijkt nu dus makkelijker te kunnen. :)

Maar voor de rest is werkt het echt ideaal, heeft me veel tijd bespaard in m'n migratie van MedaPortal(windows) naar tvheadend ook.

Nogmaals bedankt!

--Mark

**Comment by scheelings** [comment]
Ik zie het nu ook! Ik heb de info even toegevoegd. Zegt verder niet veel…alleen dat je een .ini file i.p.v. de .config kan gebruiken!

Het genereren van de TVHeadend output is nog wel work-in-progress, dus het zou best kunnen dat er soms nog wat misgaat!

Groeten,
Danny
